apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: default
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: REPO/myapp:VERSION
        #image: public/myapp:1.0.0
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: JAVA_OPTS
          value: -Xmx64m -Xms64m
        envFrom:
        - configMapRef:
            name: myapp-configmap
        # livenessProbe:
        #     httpGet:   
        #     path: /actuator/health
        #     port: http
        #     initialDelaySeconds: 40
        #     timeoutSeconds: 1
        #     periodSeconds: 15
        # readinessProbe:
        #     httpGet:
        #     path: /actuator/health
        #     port: http
        #     initialDelaySeconds: 40
        #     timeoutSeconds: 1
        #     periodSeconds: 15
